/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_PRG_H_RPCGEN
#define _RPC_PRG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct echo {
	char a[100];
};
typedef struct echo echo;

struct sort_arr {
	int b[100];
	int number_sort;
};
typedef struct sort_arr sort_arr;

struct multiply {
	int row1;
	int row2;
	int col1;
	int col2;
	int matrixA[100];
	int matrixB[100];
};
typedef struct multiply multiply;

struct result_mat {
	int matrixC[100];
};
typedef struct result_mat result_mat;

struct time_char {
	char T[100];
};
typedef struct time_char time_char;

#define RPC_PRG 0x23451111
#define RPC_PRG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define time_func 1
extern  enum clnt_stat time_func_1(int *, time_char *, CLIENT *);
extern  bool_t time_func_1_svc(int *, time_char *, struct svc_req *);
#define echo_message 2
extern  enum clnt_stat echo_message_1(echo *, echo *, CLIENT *);
extern  bool_t echo_message_1_svc(echo *, echo *, struct svc_req *);
#define listFiles 3
extern  enum clnt_stat listfiles_1(int *, char **, CLIENT *);
extern  bool_t listfiles_1_svc(int *, char **, struct svc_req *);
#define sorting 4
extern  enum clnt_stat sorting_1(sort_arr *, sort_arr *, CLIENT *);
extern  bool_t sorting_1_svc(sort_arr *, sort_arr *, struct svc_req *);
#define multiplier 5
extern  enum clnt_stat multiplier_1(multiply *, result_mat *, CLIENT *);
extern  bool_t multiplier_1_svc(multiply *, result_mat *, struct svc_req *);
extern int rpc_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define time_func 1
extern  enum clnt_stat time_func_1();
extern  bool_t time_func_1_svc();
#define echo_message 2
extern  enum clnt_stat echo_message_1();
extern  bool_t echo_message_1_svc();
#define listFiles 3
extern  enum clnt_stat listfiles_1();
extern  bool_t listfiles_1_svc();
#define sorting 4
extern  enum clnt_stat sorting_1();
extern  bool_t sorting_1_svc();
#define multiplier 5
extern  enum clnt_stat multiplier_1();
extern  bool_t multiplier_1_svc();
extern int rpc_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_echo (XDR *, echo*);
extern  bool_t xdr_sort_arr (XDR *, sort_arr*);
extern  bool_t xdr_multiply (XDR *, multiply*);
extern  bool_t xdr_result_mat (XDR *, result_mat*);
extern  bool_t xdr_time_char (XDR *, time_char*);

#else /* K&R C */
extern bool_t xdr_echo ();
extern bool_t xdr_sort_arr ();
extern bool_t xdr_multiply ();
extern bool_t xdr_result_mat ();
extern bool_t xdr_time_char ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_PRG_H_RPCGEN */
