/*
 * author : Shalini
 * The template of this client program has been generated by rpcgen.
 *
 */


#include<stdio.h>
#include<stdlib.h>

/*
* rpc_prg.h : header file contains the #define for the Program, version and Procedures  
*/


#include "rpc_prg.h"


void
rpc_prg_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	time_char result_1 ;
	int  time_func_1_arg;
	enum clnt_stat retval_2;
	echo result_2 ;
	echo  echo_message_1_arg;
	enum clnt_stat retval_3;
	char *result_3 = NULL;
	int  listfiles_1_arg;
	enum clnt_stat retval_4;
	sort_arr result_4 ;
	sort_arr  sorting_1_arg;
	enum clnt_stat retval_5;
	result_mat result_5 ;
	multiply  multiplier_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_PRG, RPC_PRG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	int choice;
    int i;
    int j;
    int flag = 1;
    char yes;
	
	/*
	* This while loop will continue until the user has no interest of 
	* performning the functions displayed in the menu. 
	*/

	while (flag ){
	
	/*
	* The user can select any one of the functions displayed in the menu 
	*/    
	printf( "Client Program \n  ");
	printf( "Please choose any one of the following functions: \n  ");
	printf( "1.  Date and Time \n  ");
	printf( "2.  Echo \n  ");
	printf( "3.  List of Files \n  ");
	printf( "4.  Sort \n  ");
	printf( "5.  Multiplier \n  ");
	printf( "Please Enter the Choice (1,2,3,4 or 5): \n  ");
	scanf("%d",&choice);
	
	/*
	* Based on the user input respective fucntion will be called from the server 
	*/ 
	
	switch(choice) {
			    case 1 : 
			     	
			     	/*
					* This function asks for current time and date from server. 
					* Upon receiving the results. It will display it to users 
					*/
			     	
					printf("Date and Time \n" );

			    	/*
					*  The function on the server will be called with arguments : input parameter, output parameter and Client variable 
					*/ 
					retval_1 = time_func_1(&time_func_1_arg, &result_1, clnt);
					
					/*
					*  If the server call is not success then the program will terminate saying "call failed" and the connection will be closed. 
					*/ 
					
					if (retval_1 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
	
					else{
						printf ("Time and Date recieved from Server : %s \n", result_1.T);
					}
					break;
					
				case 2 : 
				   
				   /*
					* This function asks for a message to send to server. 
					* Upon receiving the message back. It will display it to users 
					*/
				
				   printf( "Echo\n ");
				   printf("Enter a message to send to Client \n");
				   scanf("%s",echo_message_1_arg.a); 
				   printf( "You entered %s \n",echo_message_1_arg.a );
					
	
				   retval_2 = echo_message_1(&echo_message_1_arg, &result_2, clnt);
				    if (retval_2 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
					
					
					else{
						printf("Message received from Server : %s \n",result_2.a);
					}
					break;
					
					
				case 3:
					
				   /*
					* This function asks for the list of files in the current directory from server.
					* Upon receiving the file list back. It will display it to users 
					*/
				
					
				    printf( " List of Files \n  ");
					retval_3 = listfiles_1(&listfiles_1_arg, &result_3, clnt);
					
					if (retval_3 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
					
					
					else{
						printf("Files in the current directory:%s \n", result_3);
					}
					break;
				
				case 4 : 
				    
				    /*
					* This function takes an integer list to be sorted from the user.
					* It will send the list to the server. The server will return back the sorted list. 
					*/
				    
					printf("Sort\n ");
				    int number_sort;
					printf("Enter the number of elements to be sorted:\n ") ;
					scanf("%d",&sorting_1_arg.number_sort);
					printf("Enter elements to sort: \n");	    
					  	
					for (i =0; i <sorting_1_arg.number_sort; i++){
			        	scanf("%d", &sorting_1_arg.b[i]);
			        }
			    	
					retval_4 = sorting_1(&sorting_1_arg, &result_4, clnt);
					
					if (retval_4 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
					
					else{
				   		printf ("Sorted List recieved from Server \n");
				    
					for (i =0; i <sorting_1_arg.number_sort; i++){
			    		printf("%d",result_4.b[i]);
			    		printf("\n");
			     	}
				    }
				   break;
				   
			   case 5:
				   
				   /*
					* This function takes an two matrices as input from the user.
					* It will send the matrices to the server. The server will return back the multiplication of those matrices. 
					*/
				   printf( "Multiplier \n  ");
                   printf( "Enter the row length for Matrix A\n  ");
                   scanf("%d",&multiplier_1_arg.row1);
                   printf( "Enter the column length for Matrix A\n  ");
                   scanf("%d",&multiplier_1_arg.col1);
				   printf( "Enter the row length for Matrix B\n  ");
				   scanf("%d",&multiplier_1_arg.row2);
				   printf( "Enter the column length for Matrix B\n  ");
				   scanf("%d",&multiplier_1_arg.col2);
                   
                   /*
					* Checks the size of the matrices to perform multiplication
					* The matrixA's column must be equal to matrixB's row for multiplication 
					*/
					
                   if (multiplier_1_arg.row2 != multiplier_1_arg.col1){
                   	
                   	printf("Sorry the matrices size are not aligned \n");
                   	break;
				   }
                   
				   printf("Enter the Values for Matrix A  \n :");
                   for (i =0 ;i <multiplier_1_arg.row1 * multiplier_1_arg.col1 ; i++){
                   		scanf("%d",&multiplier_1_arg.matrixA[i]);
					   }
                    printf("Enter the Values for Matrix B  \n :");
                   for (i =0 ;i < multiplier_1_arg.row2 * multiplier_1_arg.col2; i++){
                   		scanf("%d",&multiplier_1_arg.matrixB[i]);
					   }
                   	
				   
			   	  retval_5 = multiplier_1(&multiplier_1_arg, &result_5, clnt);
				   if (retval_5 != RPC_SUCCESS) {
						clnt_perror (clnt, "call failed");
					}
	
				  else{
			      	
			      		printf("Matrix received from server \n :");
                        for (i =0 ;i < multiplier_1_arg.row1 * multiplier_1_arg.col2; i++){
                     	
                   		printf("%d  ",result_5.matrixC[i]);
                   		printf("\n");
					   }
					   printf("\n");
                   	
				      }
					           
				      break;
				
			/*
			* If none of the choice has been selected then it show error message.
			*/			   	
			default:
				printf("Invalid Choice \n");
			}
		
    printf("Enter Y or N to continue\n");
    scanf(" %c", &yes);
    if (yes == 'N') {
        flag = 0;
		}
	if (yes != 'N' && yes != 'Y'){
		printf ("Not a valid choice\n");
		flag = 0;
	}	
		
		/*
		* Once the program is finished the connection will be closed and the client object will be destroyed  
		*/
}
		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */
		}


int
main (int argc, char *argv[])
{
	
	/*
	* host variable holds the ip address of the server which is given in command line during the program execution.
	*/	
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	/*
	* Activates the communication with server.
	*/	
	rpc_prg_1 (host);
exit (0);
}
