/*
 * author : Shalini
 * The template of this server program has been generated by rpcgen.
 *
 */


#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/dir.h>
#include <string.h>
#include <time.h>

/*
* rpc_prg.h : header file contains the #define for the Program, version and Procedures  
*/

#include "rpc_prg.h"

/*
* Based on Client's request, the respective function will be excuted upon successful connection
* This program supports multiple clients. Concurrent requests can be processed 
*/




bool_t
time_func_1_svc(int *argp, time_char *result, struct svc_req *rqstp)
{
		/*
		* This function send the current time and date to the client 
		* through the output parameter. 
		*/
				
		bool_t retval;	
	    time_t current_time;
	    current_time = time(NULL);
	    char* field = asctime(localtime(&current_time));
		strcpy(result->T, field);

	return 1;
}

char* listOfFiles(int id)
	{
		
		/*
		* This function collects the list of files in the current directory 
		* and return the list 
		*/
	   
	    DIR *directory_list;
	    struct direct *d;
	    char* list="";
	    directory_list = opendir(".");
	    if (directory_list == NULL) {
	        return "NULL";
	    }
	
	   while ((d = readdir(directory_list))!=NULL) {
	        char *temp=malloc((strlen(list)+2)*sizeof(char));
	        strcpy(temp,list);
	        temp=strcat(temp,"\n");
	        list=malloc((strlen(temp)+strlen(d->d_name)+1)*sizeof(char));
	        list=strcat(temp,d->d_name);
	    }
	    closedir(directory_list);
	    return list;
	}
	

bool_t
echo_message_1_svc(echo *argp, echo *result, struct svc_req *rqstp)
{
	
	/*
	* This function echo back the message the current sends 
	* through the output parameter. 
	*/
	
	bool_t retval; 
	*result =  *argp;
	return 1;
}

bool_t
listfiles_1_svc(int *argp, char **result, struct svc_req *rqstp)
{
   
   	/*
	* This function retuns the list of files in the current directory to the client 
	* through the output parameter. 
	*/
    
	bool_t retval;
	char * listF = (listOfFiles(*argp));
	*result = listF;
	return 1;
 
}

bool_t
sorting_1_svc(sort_arr *argp, sort_arr *result, struct svc_req *rqstp)
{


		/*
		* This function accepts an integer list and retuns the sorted list to the client 
		* through the output parameter. 
		*/

    	bool_t retval;
	
	    int num = argp->number_sort;
		int i;
		int j;
	    int temp;	    
	
		for (i = 1; i < num; i++) {
	      temp = argp->b[i];
	      j = i - 1;
	      while ((temp < argp->b[j]) && (j >= 0)) {
	         argp->b[j + 1] = argp->b[j];
	         j = j - 1;
	      }
	      argp->b[j + 1] = temp;
	   }
	
		 *result = *argp;

	return 1;
}

bool_t
multiplier_1_svc(multiply *argp, result_mat *result, struct svc_req *rqstp)
{
	
	   	/*
		* This function accepts two matrices in the form of array and 
		* convert them to two dimensional array and perfrom matrix multiplication and 
		* send the resulting matrix as array to client list 
		* through the output parameter. 
		*/
		 	
		bool_t retval;
		int i,j,k,sum =0;
		int A[100][100],B[100][100],C[100][100];
		
		/*
		* Converting the array given from the Client to matrix
		*/
		
		k=0;
		for (i=0;i<argp->row1;i++){
			for(j=0;j<argp->col1;j++){
				A[i][j]=argp->matrixA[k];
				k++;
			}
		}
	
	  k=0;
	  for (i=0;i<argp->row2;i++){
			for(j=0;j<argp->col2;j++){
				B[i][j]=argp->matrixB[k];
				k++;
			}
		}	
		
		/*
		* Matrix Multplication
		*/
	   for ( i = 0 ; i < argp->row1 ; i++ )
	    {
	      for ( j = 0 ; j < argp->col2 ; j++ )
	      {
	        for ( k = 0 ; k < argp->row2 ; k++ )
	        {
	          sum = sum + A[i][k]*B[k][j];
	        }
	 
	        C[i][j] = sum;
	        sum = 0;
	      }
	    }
	    
	    /*
		* Converting the result matrix into array and send the array to the client
		*/
		
	    k=0;
	    for (i=0;i<argp->row1;i++)
		{
			for(j=0;j<argp->col2;j++)
			{			
			result->matrixC[k] = C[i][j];
				k++;
			}
		}
	
	
		return 1;
}

int
rpc_prg_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);
	return 1;
}
