/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_prg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
time_func_1(int *argp, time_char *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, time_func,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_time_char, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
echo_message_1(echo *argp, echo *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, echo_message,
		(xdrproc_t) xdr_echo, (caddr_t) argp,
		(xdrproc_t) xdr_echo, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
listfiles_1(int *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, listFiles,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
sorting_1(sort_arr *argp, sort_arr *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, sorting,
		(xdrproc_t) xdr_sort_arr, (caddr_t) argp,
		(xdrproc_t) xdr_sort_arr, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
multiplier_1(multiply *argp, result_mat *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, multiplier,
		(xdrproc_t) xdr_multiply, (caddr_t) argp,
		(xdrproc_t) xdr_result_mat, (caddr_t) clnt_res,
		TIMEOUT));
}
